In [131]:
import pandas as pd
import numpy as np
import sklearn.preprocessing as prp
import sklearn.model_selection as ms
import sklearn.ensemble as ske
import sklearn.metrics as skm

In [132]:
file='Downloads/DataSET/stock portfolio performance.csv'

In [133]:
ptf=pd.read_csv(file, sep=';')

In [134]:
ptf.head(15)

ID  Large B/P   Large ROE   Large S/P   \
0    1       1,000       0,000       0,000   
1    2       0,000       1,000       0,000   
2    3       0,000       0,000       1,000   
3    4       0,000       0,000       0,000   
4    5       0,000       0,000       0,000   
5    6       0,000       0,000       0,000   
6    7       0,500       0,500       0,000   
7    8       0,500       0,000       0,500   
8    9       0,000       0,500       0,500   
9   10       0,500       0,000       0,000   
10  11       0,000       0,500       0,000   
11  12       0,000       0,000       0,500   
12  13       0,500       0,000       0,000   
13  14       0,000       0,500       0,000   
14  15       0,000       0,000       0,500   

    Large Return Rate in the last quarter   Large Market Value   \
0                                    0,000                0,000   
1                                    0,000                0,000   
2                                    0,000                0,000   
3                                    1,000                0,000   
4                                    0,000                1,000   
5                                    0,000                0,000   
6                                    0,000                0,000   
7                                    0,000                0,000   
8                                    0,000                0,000   
9                                    0,500                0,000   
10                                   0,500                0,000   
11                                   0,500                0,000   
12                                   0,000                0,500   
13                                   0,000                0,500   
14                                   0,000                0,500   

    Small systematic Risk Annual Return Excess Return  
0                   0,000        13,90%         1,00%  
1                   0,000        14,30%         1,00%  
2                   0,000        17,30%         1,80%  
3                   0,000         9,60%        -0,20%  
4                   0,000         9,60%         0,10%  
5                   1,000         7,00%        -0,50%  
6                   0,000        19,50%         2,60%  
7                   0,000        16,40%         1,60%  
8                   0,000        18,50%         2,20%  
9                   0,000        15,00%         1,50%  
10                  0,000        15,90%         1,50%  
11                  0,000        17,00%         1,80%  
12                  0,000        14,00%         1,10%  
13                  0,000        12,30%         0,80%  
14                  0,000        14,50%         1,30%

In [135]:
print(ptf.dtypes)
headers= ptf.columns.values.tolist()
headers

ID                                          int64
 Large B/P                                 object
 Large ROE                                 object
 Large S/P                                 object
 Large Return Rate in the last quarter     object
 Large Market Value                        object
 Small systematic Risk                     object
Annual Return                              object
Excess Return                              object
dtype: object


['ID',
 ' Large B/P ',
 ' Large ROE ',
 ' Large S/P ',
 ' Large Return Rate in the last quarter ',
 ' Large Market Value ',
 ' Small systematic Risk',
 'Annual Return',
 'Excess Return']

In [136]:
##Data wrangling and preparation
Features= headers[1:7]
perf= headers[8]

for col in Features:
    if ptf[col].dtypes == 'object':
        ptf[col]= [str.replace(',','.') for str in ptf[col]]
        ptf[[col]]= ptf[[col]].astype('float')

ptf[perf]=[a.strip('%') for a in ptf[perf]]

ptf[perf]= [str.replace(',','.') for str in ptf[perf]]

ptf[[perf]]=ptf[[perf]].astype('float')

ptf.dtypes

ptf[[perf]]= ptf[[perf]]/100

In [194]:
print('shape : ',np.shape(Features))
ptf.head(10)

shape :  (6,)


ID   Large B/P    Large ROE    Large S/P   \
0   1          1.0          0.0          0.0   
1   2          0.0          1.0          0.0   
2   3          0.0          0.0          1.0   
3   4          0.0          0.0          0.0   
4   5          0.0          0.0          0.0   
5   6          0.0          0.0          0.0   
6   7          0.5          0.5          0.0   
7   8          0.5          0.0          0.5   
8   9          0.0          0.5          0.5   
9  10          0.5          0.0          0.0   

    Large Return Rate in the last quarter    Large Market Value   \
0                                      0.0                   0.0   
1                                      0.0                   0.0   
2                                      0.0                   0.0   
3                                      1.0                   0.0   
4                                      0.0                   1.0   
5                                      0.0                   0.0   
6                                      0.0                   0.0   
7                                      0.0                   0.0   
8                                      0.0                   0.0   
9                                      0.5                   0.0   

    Small systematic Risk Annual Return  Excess Return  
0                     0.0        13,90%          0.010  
1                     0.0        14,30%          0.010  
2                     0.0        17,30%          0.018  
3                     0.0         9,60%         -0.002  
4                     0.0         9,60%          0.001  
5                     1.0         7,00%         -0.005  
6                     0.0        19,50%          0.026  
7                     0.0        16,40%          0.016  
8                     0.0        18,50%          0.022  
9                     0.0        15,00%          0.015

In [138]:
X=ptf[Features].values
y=ptf[perf].values
print(X[0:6])
print(y[0:6])
print(X.shape)
print(y.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[ 0.01   0.01   0.018 -0.002  0.001 -0.005]
(63, 6)
(63,)


In [139]:
np.random.seed(4000)
ligne= range(X.shape[0])
ligne=ms.train_test_split(ligne,test_size=0.3)
X_train=np.array(X[ligne[0],:])
ytrain=np.ravel(y[ligne[0]])
X_test=np.array(X[ligne[1],:])
ytest=np.ravel(y[ligne[1]])
print(X_train.shape)
print(X_test.shape)
print(ytrain.shape)
print(ytest.shape)

(44, 6)
(19, 6)
(44,)
(19,)


In [140]:
import sklearn.linear_model as lm

In [141]:
lrm= lm.LinearRegression(fit_intercept= False)
lrm=lrm.fit(X_train,ytrain)

In [142]:
Yhat=lrm.predict(X_test)

In [221]:
print('r2 score: ',skm.r2_score(ytest,Yhat))
print('model coefficients: ',lrm.coef_)
print('intercept: ',lrm.intercept_)
print('variance explained: ',skm.explained_variance_score(ytest,Yhat))
print('RMSE: ',np.sqrt(skm.mean_squared_error(ytest,Yhat)))

r2 score:  0.4291620143586613
model coefficients:  [0.01933084 0.02235916 0.02512279 0.00673793 0.005288   0.00532828]
intercept:  0.0
variance explained:  0.5413379149089123
RMSE:  0.005400162645339042


In [222]:
###Method 2 cross validation
score=ms.cross_val_score(lrm,X,y,cv=4)
print('cross validation score: ',score)
print('mean cross validation score: ',score.mean())

cross validation score:  [-0.13598597  0.70052025  0.53038126 -1.92105804]
mean cross validation score:  -0.20653562559952887


In [227]:
##Method 3: Random Forest regressor
rfr=ske.RandomForestRegressor(n_estimators=100,min_samples_leaf=2,min_samples_split=2,random_state=4,oob_score=True)
fitrf=rfr.fit(X_train,ytrain)
score=ms.cross_val_score(fitrf,X,y, cv=4)

In [228]:
print('score of cross validation :',score)
print('mean score: ',score.mean())
explanation=fitrf.feature_importances_
print('feature explanation: ',explanation)
summary=pd.DataFrame(data=explanation, index=Features,columns=['Percentage'])
print(fitrf.oob_score_)

score of cross validation : [0.56341539 0.92661721 0.86710305 0.35024291]
mean score:  0.6768446400925143
feature explanation:  [0.15589803 0.24321942 0.25876164 0.07177542 0.1296538  0.1406917 ]
0.6706621327097481


In [229]:
summary

Percentage
 Large B/P                                 0.155898
 Large ROE                                 0.243219
 Large S/P                                 0.258762
 Large Return Rate in the last quarter     0.071775
 Large Market Value                        0.129654
 Small systematic Risk                     0.140692

In [244]:
model_1=fitrf.estimators_[5]

In [263]:
from sklearn.tree import export_graphviz
import pydotplus

In [273]:
export_graphviz(model_1,out_file='reg.dot',feature_names=Features,precision=1,special_characters=True,leaves_parallel= True,rounded=True)

In [275]:
graph=pydotplus.graph_from_dot_file('reg.dot')

In [276]:
graph.write_pdf('reg.pdf')

True

In [277]:
import IPython.display as dis

In [279]:
dis.display_pdf('reg.pdf')

In [201]:
##Method 4 Decision Regressor
from sklearn.tree import DecisionTreeRegressor

In [205]:
dr=DecisionTreeRegressor(min_samples_leaf=2,min_samples_split=2,random_state=23)
drf=dr.fit(X_train,ytrain)

In [206]:
score_3=ms.cross_val_score(drf,X,y,cv=4)

In [207]:
print('score of decision regressor: ',score_3)
print('mean score of the model: ', score_3.mean())
print('features importances : ',dr.feature_importances_)

score of decision regressor:  [0.80664709 0.7526787  0.83943895 0.00728356]
mean score of the model:  0.6015120755483895
features importances :  [0.23687379 0.35674624 0.31283918 0.00410807 0.08282779 0.00660492]


In [208]:
summary_2=pd.DataFrame(index=Features,data=dr.feature_importances_)
summary_2

0
 Large B/P                               0.236874
 Large ROE                               0.356746
 Large S/P                               0.312839
 Large Return Rate in the last quarter   0.004108
 Large Market Value                      0.082828
 Small systematic Risk                   0.006605

In [209]:
##GRID SEARCH To select best hyperparameters
rf2=ske.RandomForestRegressor()
parms={'n_estimators':[100,120,150,200],'min_samples_leaf':[2,4,5,10],'min_samples_split':[2,3,5,6]}

In [210]:
srfr2=ms.GridSearchCV(rf2, param_grid=parms, scoring='r2',cv=4)

In [211]:
srfr2.fit(X,y)

/Users/soloheryramilijaona/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=4, error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators='warn', n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'min_samples_leaf': [2, 4, 5, 1

In [212]:
srfr2.cv_results_.keys()

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_min_samples_leaf', 'param_min_samples_split', 'param_n_estimators', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [213]:
print('best sample leaf :' ,srfr2.best_estimator_.min_samples_leaf)
print('best number of estimators : ',srfr2.best_estimator_.n_estimators)
print('best sample split number : ', srfr2.best_estimator_.min_samples_split)

best sample leaf : 2
best number of estimators :  100
best sample split number :  2


In [214]:
##Best hyperparameters for decision tree regressor
dtr= DecisionTreeRegressor()
prms={'min_samples_split':[2,4,6,8],'min_samples_leaf':[2,4,6,8]}
dts=ms.GridSearchCV(dtr,param_grid=prms,scoring='r2',cv=4)

In [215]:
dts.fit(X,y)

/Users/soloheryramilijaona/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=4, error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=None,
             param_grid={'min_samples_leaf': [2, 4, 6, 8],
                         'min_samples_split': [2, 4, 6, 8]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             sco

In [216]:
print('best estimator for leaf :', dts.best_estimator_.min_samples_leaf)
print('best estimator for split : ', dts.best_estimator_.min_samples_split)

best estimator for leaf : 2
best estimator for split :  4


In [217]:
dtr2=DecisionTreeRegressor(min_samples_leaf=2,min_samples_split=4)

In [218]:
score_4=ms.cross_val_score(dtr2,X,y,cv=4)